export const LOCALE_KEYS = {

  // Navbar
  HOME: "HOME",
  SERVICE: "SERVICE",
  ABOUT_US: "ABOUT_US",
  TEAMS: "TEAMS",
  CAREER: "CAREER",
  BLOG: "BLOG",
  CONTACT_US: "CONTACT_US",

  // Footer - Sections
  QUICK_LINKS: "QUICK_LINKS",
  SERVICES: "SERVICES",
  FOLLOW_US: "FOLLOW_US",
  GET_IN_TOUCH: "GET_IN_TOUCH",

  // Footer - Services List
  WEB_DEV: "WEB_DEV",
  UI_UX: "UI_UX",
  MOBILE_APP: "MOBILE_APP",
  CLOUD_WEB: "CLOUD_WEB",
  IT_CONSULT: "IT_CONSULT",

  // Footer - Bottom
  COPYRIGHT: "COPYRIGHT",
  PRIVACY_POLICY: "PRIVACY_POLICY",
  TERMS_OF_SERVICE: "TERMS_OF_SERVICE",
  TURN_IDEAS: "TURN_IDEAS",
  TURN_IDEAS_DESC: "TURN_IDEAS_DESC",
  LETS_GET_STARTED: "LETS_GET_STARTED",


  //Banner
  ACHIEVEMENTS: "ACHIEVEMENTS",
  ACHIEVEMENTS_DESC: "ACHIEVEMENTS_DESC",
  BUILD_YOUR: "BUILD_YOUR",
  DREAM_PRODUCT: "DREAM_PRODUCT",
  FASTER_DELIVERY: "FASTER_DELIVERY",
  BANNER_DESCRIPTION: "BANNER_DESCRIPTION",

  //Banner Card
  WEB_APP_TITLE: "WEB_APP_TITLE",
  WEB_APP_DESC: "WEB_APP_DESC",
  IT_CONSULTING_TITLE: "IT_CONSULTING_TITLE",
  IT_CONSULTING_DESC: "IT_CONSULTING_DESC",
  CUSTOM_SOFTWARE_TITLE: "CUSTOM_SOFTWARE_TITLE",
  CUSTOM_SOFTWARE_DESC: "CUSTOM_SOFTWARE_DESC",
  IOT_TITLE: "IOT_TITLE",
  IOT_DESC: "IOT_DESC",
  UI_UX_TITLE: "UI_UX_TITLE",
  UI_UX_DESC: "UI_UX_DESC",
  CYBERSECURITY_TITLE: "CYBERSECURITY_TITLE",
  CYBERSECURITY_DESC: "CYBERSECURITY_DESC",

  //transform ideas
  TRANSFORM_IDEAS_HEADER: "transform_title",
  LETS_TALK: "LETS_TALK",

  FINTECH_TITLE: "FINTECH_TITLE",
  FINTECH_DESC: "FINTECH_DESC",
  HEALTHCARE_TITLE: "HEALTHCARE_TITLE",
  HEALTHCARE_DESC: "HEALTHCARE_DESC",
  AUTOMATION_TITLE: "AUTOMATION_TITLE",
  AUTOMATION_DESC: "AUTOMATION_DESC",
  ECOMMERCE_TITLE: "ECOMMERCE_TITLE",
  ECOMMERCE_DESC: "ECOMMERCE_DESC",
  TELCO_TITLE: "TELCO_TITLE",
  TELCO_DESC: "TELCO_DESC",
  STARTUP_TITLE: "STARTUP_TITLE",
  STARTUP_DESC: "STARTUP_DESC",

  //trusted by
  TRUSTED_BY: "TRUSTED_BY",

  //optimization section 
  // Optimized Development Section
  OPT_DEV_INTELLIGENT_CODING_TITLE: "OPT_DEV_INTELLIGENT_CODING_TITLE",
  OPT_DEV_INTELLIGENT_CODING_SUBTITLE: "OPT_DEV_INTELLIGENT_CODING_SUBTITLE",
  OPT_DEV_INTELLIGENT_CODING_DESC: "OPT_DEV_INTELLIGENT_CODING_DESC",

  OPT_DEV_BULLETPROOF_QA_TITLE: "OPT_DEV_BULLETPROOF_QA_TITLE",
  OPT_DEV_BULLETPROOF_QA_SUBTITLE: "OPT_DEV_BULLETPROOF_QA_SUBTITLE",
  OPT_DEV_BULLETPROOF_QA_DESC: "OPT_DEV_BULLETPROOF_QA_DESC",

  OPT_DEV_PEAK_PERFORMANCE_TITLE: "OPT_DEV_PEAK_PERFORMANCE_TITLE",
  OPT_DEV_PEAK_PERFORMANCE_SUBTITLE: "OPT_DEV_PEAK_PERFORMANCE_SUBTITLE",
  OPT_DEV_PEAK_PERFORMANCE_DESC: "OPT_DEV_PEAK_PERFORMANCE_DESC",

  OPT_DEV_ZERO_DOWNTIME_TITLE: "OPT_DEV_ZERO_DOWNTIME_TITLE",
  OPT_DEV_ZERO_DOWNTIME_SUBTITLE: "OPT_DEV_ZERO_DOWNTIME_SUBTITLE",
  OPT_DEV_ZERO_DOWNTIME_DESC: "OPT_DEV_ZERO_DOWNTIME_DESC",

  // Optimized Development Left
  OPT_DEV_HEADING: "OPT_DEV_HEADING",
  OPT_DEV_DESCRIPTION: "OPT_DEV_DESCRIPTION",
  GET_STARTED: "GET_STARTED",

  // Case Studies
  CASE_STUDIES_TITLE: "CASE_STUDIES_TITLE",
  CASE_STUDIES_SUBTITLE: "CASE_STUDIES_SUBTITLE",
  CASE_STUDIES_BUTTON: "CASE_STUDIES_BUTTON",
  // Case Studies Stats
  CASE_STATS_CLIENT_SATISFACTION: "CASE_STATS_CLIENT_SATISFACTION",
  CASE_STATS_ROI: "CASE_STATS_ROI",
  CASE_STATS_DELIVERY: "CASE_STATS_DELIVERY",
  CASESTUDIES: {
    BUTTON1: {
      UXUI: "CASESTUDIES.BUTTON1.UXUI",
      WEB: "CASESTUDIES.BUTTON1.WEB",
      MOBILE: "CASESTUDIES.BUTTON1.MOBILE",
      BRANDING: "CASESTUDIES.BUTTON1.BRANDING",
    },
    BUTTON2: {
      MOBILE: "CASESTUDIES.BUTTON2.MOBILE",
      ECOMMERCE: "CASESTUDIES.BUTTON2.ECOMMERCE",
      HEALTHCARE: "CASESTUDIES.BUTTON2.HEALTHCARE",
      WEB: "CASESTUDIES.BUTTON2.WEB",
      MARKETING: "CASESTUDIES.BUTTON2.MARKETING",
    },
    TITLE: {
      SOCIAL: "CASESTUDIES.TITLE.SOCIAL",
      FASHION: "CASESTUDIES.TITLE.FASHION",
      HEALTH: "CASESTUDIES.TITLE.HEALTH",
      LEARNING: "CASESTUDIES.TITLE.LEARNING",
    },
    DESCRIPTION: {
      SOCIAL: "CASESTUDIES.DESCRIPTION.SOCIAL",
      FASHION: "CASESTUDIES.DESCRIPTION.FASHION",
      HEALTH: "CASESTUDIES.DESCRIPTION.HEALTH",
      LEARNING: "CASESTUDIES.DESCRIPTION.LEARNING",
    },
    DESCRIPTION1: {
      SOCIAL: "CASESTUDIES.DESCRIPTION1.SOCIAL",
      FASHION: "CASESTUDIES.DESCRIPTION1.FASHION",
      HEALTH: "CASESTUDIES.DESCRIPTION1.HEALTH",
      LEARNING: "CASESTUDIES.DESCRIPTION1.LEARNING",
    },
    VIEW: "CASESTUDIES.VIEW",
  },
  ABOUT: "ABOUT",
  WHO: "WHO",
  ABOUT_TITLE: "ABOUT_TITLE",
  ABOUT_DESCRIPTION: "ABOUT_DESCRIPTION",
  STATS_PROJECTS: "STATS_PROJECTS",
  STATS_YEARS: "STATS_YEARS",
  WHO_TITLE: "WHO_TITLE",
  WHO_DESCRIPTION: "WHO_DESCRIPTION",
  STATS_TEAM: "STATS_TEAM",
  STATS_INDUSTRIES: "STATS_INDUSTRIES",
  OUR_GLOBAL_FAMILY_TITLE: "our_global_family_title",
  OUR_GLOBAL_FAMILY_SUBTITLE: "our_global_family_subtitle",
  CLEARSTEPS_TITLE: "CLEARSTEPS_TITLE",
  CLEARSTEPS_DESCRIPTION: "CLEARSTEPS_DESCRIPTION",
  CLEARSTEPS_BUTTON: "CLEARSTEPS_BUTTON",
  CLEARSTEPS_CARD: {
    CARD1: {
      TITLE: "CLEARSTEPS_CARD1_TITLE",
      STEP: "CLEARSTEPS_CARD1_STEP",
      DES1: "CLEARSTEPS_CARD1_DES1",
      DES2: "CLEARSTEPS_CARD1_DES2",
      DES3: "CLEARSTEPS_CARD1_DES3",
    },
    CARD2: {
      TITLE: "CLEARSTEPS_CARD2_TITLE",
      STEP: "CLEARSTEPS_CARD2_STEP",
      DES1: "CLEARSTEPS_CARD2_DES1",
      DES2: "CLEARSTEPS_CARD2_DES2",
      DES3: "CLEARSTEPS_CARD2_DES3",
    },
    CARD3: {
      TITLE: "CLEARSTEPS_CARD3_TITLE",
      STEP: "CLEARSTEPS_CARD3_STEP",
      DES1: "CLEARSTEPS_CARD3_DES1",
      DES2: "CLEARSTEPS_CARD3_DES2",
      DES3: "CLEARSTEPS_CARD3_DES3",
    },
    CARD4: {
      TITLE: "CLEARSTEPS_CARD4_TITLE",
      STEP: "CLEARSTEPS_CARD4_STEP",
      DES1: "CLEARSTEPS_CARD4_DES1",
      DES2: "CLEARSTEPS_CARD4_DES2",
      DES3: "CLEARSTEPS_CARD4_DES3",
    },
  },
  CLIENTS: {
    HEADER_TITLE: "CLIENTS_HEADER_TITLE",
    HEADER_SUBTITLE: "CLIENTS_HEADER_SUBTITLE",
    VIEW_ALL: "CLIENTS_VIEW_ALL",
    TESTIMONIALS: {
      1: {
        NAME: "CLIENT_1_NAME",
        ROLE: "CLIENT_1_ROLE",
        FEEDBACK: "CLIENT_1_FEEDBACK"
      },
      2: {
        NAME: "CLIENT_2_NAME",
        ROLE: "CLIENT_2_ROLE",
        FEEDBACK: "CLIENT_2_FEEDBACK"
      },
      3: {
        NAME: "CLIENT_3_NAME",
        ROLE: "CLIENT_3_ROLE",
        FEEDBACK: "CLIENT_3_FEEDBACK"
      },
      4: {
        NAME: "CLIENT_4_NAME",
        ROLE: "CLIENT_4_ROLE",
        FEEDBACK: "CLIENT_4_FEEDBACK"
      },
      5: {
        NAME: "CLIENT_5_NAME",
        ROLE: "CLIENT_5_ROLE",
        FEEDBACK: "CLIENT_5_FEEDBACK"
      },
      6: {
        NAME: "CLIENT_6_NAME",
        ROLE: "CLIENT_6_ROLE",
        FEEDBACK: "CLIENT_6_FEEDBACK"
      }
    }
  },
  RATING_STAR: "CLIENTS_RATING_STAR",
  COMPLETE_SUPPORT_TITLE: "COMPLETE_SUPPORT_TITLE",
  BUTTON_TITLE: "button_title",
  HEADING: "heading",
  DESCRIPTION: "description",
  ROLE: "role",
  EMAIL: "email",
  PHONE: "phone",
  FAQ: {
    TITLE: "faq.title",
    SUBTITLE: "faq.subtitle",
    ITEMS: {
      Q1: "faq.items.q1.question",
      A1: "faq.items.q1.answer",
      Q2: "faq.items.q2.question",
      A2: "faq.items.q2.answer",
      Q3: "faq.items.q3.question",
      A3: "faq.items.q3.answer",
      Q4: "faq.items.q4.question",
      A4: "faq.items.q4.answer",
      Q5: "faq.items.q5.question",
      A5: "faq.items.q5.answer",
    },
  },
  BUTTON_TITLE: "button_title_contact",
  HEADING: "heading_contact",
  DESCRIPTION: "description_contact",
  FULL_NAME: "full_name",
  FULL_NAME_PLACEHOLDER: "full_name_placeholder",
  EMAIL: "email_contact",
  EMAIL_PLACEHOLDER: "email_placeholder",
  SUBJECT: "subject",
  SUBJECT_PLACEHOLDER: "subject_placeholder",
  MESSAGE: "message",
  MESSAGE_PLACEHOLDER: "message_placeholder",
  PRIVACY_TEXT: "privacy_text",
  CONFIRM_TEXT: "confirm_text",
  SUBMIT: "submit",
  SUCCESS: "success",

};


export const t = (key, values = {}) => {
  return key;
};
