export const LOCALE_KEYS = {

  // Navbar
  HOME: "HOME",
  SERVICE: "SERVICE",
  ABOUT_US: "ABOUT_US",
  TEAMS: "TEAMS",
  CAREER: "CAREER",
  BLOG: "BLOG",
  CONTACT_US: "CONTACT_US",

  // Footer - Sections
  QUICK_LINKS: "QUICK_LINKS",
  SERVICES: "SERVICES",
  FOLLOW_US: "FOLLOW_US",
  GET_IN_TOUCH: "GET_IN_TOUCH",

  // Footer - Services List
  WEB_DEV: "WEB_DEV",
  UI_UX: "UI_UX",
  MOBILE_APP: "MOBILE_APP",
  CLOUD_WEB: "CLOUD_WEB",
  IT_CONSULT: "IT_CONSULT",

  // Footer - Bottom
  COPYRIGHT: "COPYRIGHT",
  PRIVACY_POLICY: "PRIVACY_POLICY",
  TERMS_OF_SERVICE: "TERMS_OF_SERVICE",
  TURN_IDEAS: "TURN_IDEAS",
  TURN_IDEAS_DESC: "TURN_IDEAS_DESC",
  GET_STARTED: "GET_STARTED",


  //Banner
  ACHIEVEMENTS: "ACHIEVEMENTS",
  ACHIEVEMENTS_DESC: "ACHIEVEMENTS_DESC",
  BUILD_YOUR: "BUILD_YOUR",
  DREAM_PRODUCT: "DREAM_PRODUCT",
  FASTER_DELIVERY: "FASTER_DELIVERY",
  BANNER_DESCRIPTION: "BANNER_DESCRIPTION",

  //Banner Card
  WEB_APP_TITLE: "WEB_APP_TITLE",
  WEB_APP_DESC: "WEB_APP_DESC",
  IT_CONSULTING_TITLE: "IT_CONSULTING_TITLE",
  IT_CONSULTING_DESC: "IT_CONSULTING_DESC",
  CUSTOM_SOFTWARE_TITLE: "CUSTOM_SOFTWARE_TITLE",
  CUSTOM_SOFTWARE_DESC: "CUSTOM_SOFTWARE_DESC",
  IOT_TITLE: "IOT_TITLE",
  IOT_DESC: "IOT_DESC",
  UI_UX_TITLE: "UI_UX_TITLE",
  UI_UX_DESC: "UI_UX_DESC",
  CYBERSECURITY_TITLE: "CYBERSECURITY_TITLE",
  CYBERSECURITY_DESC: "CYBERSECURITY_DESC",

  //transform ideas
  TRANSFORM_IDEAS_HEADER: "transform_title",
  LETS_TALK: "LETS_TALK",

  FINTECH_TITLE: "FINTECH_TITLE",
  FINTECH_DESC: "FINTECH_DESC",
  HEALTHCARE_TITLE: "HEALTHCARE_TITLE",
  HEALTHCARE_DESC: "HEALTHCARE_DESC",
  AUTOMATION_TITLE: "AUTOMATION_TITLE",
  AUTOMATION_DESC: "AUTOMATION_DESC",
  ECOMMERCE_TITLE: "ECOMMERCE_TITLE",
  ECOMMERCE_DESC: "ECOMMERCE_DESC",
  TELCO_TITLE: "TELCO_TITLE",
  TELCO_DESC: "TELCO_DESC",
  STARTUP_TITLE: "STARTUP_TITLE",
  STARTUP_DESC: "STARTUP_DESC",

  //trusted by
  TRUSTED_BY: "TRUSTED_BY",

  //optimization section 
  // Optimized Development Section
  OPT_DEV_INTELLIGENT_CODING_TITLE: "OPT_DEV_INTELLIGENT_CODING_TITLE",
  OPT_DEV_INTELLIGENT_CODING_SUBTITLE: "OPT_DEV_INTELLIGENT_CODING_SUBTITLE",
  OPT_DEV_INTELLIGENT_CODING_DESC: "OPT_DEV_INTELLIGENT_CODING_DESC",

  OPT_DEV_BULLETPROOF_QA_TITLE: "OPT_DEV_BULLETPROOF_QA_TITLE",
  OPT_DEV_BULLETPROOF_QA_SUBTITLE: "OPT_DEV_BULLETPROOF_QA_SUBTITLE",
  OPT_DEV_BULLETPROOF_QA_DESC: "OPT_DEV_BULLETPROOF_QA_DESC",

  OPT_DEV_PEAK_PERFORMANCE_TITLE: "OPT_DEV_PEAK_PERFORMANCE_TITLE",
  OPT_DEV_PEAK_PERFORMANCE_SUBTITLE: "OPT_DEV_PEAK_PERFORMANCE_SUBTITLE",
  OPT_DEV_PEAK_PERFORMANCE_DESC: "OPT_DEV_PEAK_PERFORMANCE_DESC",

  OPT_DEV_ZERO_DOWNTIME_TITLE: "OPT_DEV_ZERO_DOWNTIME_TITLE",
  OPT_DEV_ZERO_DOWNTIME_SUBTITLE: "OPT_DEV_ZERO_DOWNTIME_SUBTITLE",
  OPT_DEV_ZERO_DOWNTIME_DESC: "OPT_DEV_ZERO_DOWNTIME_DESC",

  // Optimized Development Left
  OPT_DEV_HEADING: "OPT_DEV_HEADING",
  OPT_DEV_DESCRIPTION: "OPT_DEV_DESCRIPTION",
  OPT_DEV_BUTTON: "OPT_DEV_BUTTON",
};


export const t = (key, values = {}) => {
  return key;
};
