export const LOCALE_KEYS = {

  // Navbar
  HOME: "HOME",
  SERVICE: "SERVICE",
  ABOUT_US: "ABOUT_US",
  TEAMS: "TEAMS",
  CAREER: "CAREER",
  BLOG: "BLOG",
  CONTACT_US: "CONTACT_US",

  // Footer - Sections
  QUICK_LINKS: "QUICK_LINKS",
  SERVICES: "SERVICES",
  FOLLOW_US: "FOLLOW_US",
  GET_IN_TOUCH: "GET_IN_TOUCH",

  // Footer - Services List
  WEB_DEV: "WEB_DEV",
  UI_UX: "UI_UX",
  MOBILE_APP: "MOBILE_APP",
  CLOUD_WEB: "CLOUD_WEB",
  IT_CONSULT: "IT_CONSULT",

  // Footer - Bottom
  COPYRIGHT: "COPYRIGHT",
  PRIVACY_POLICY: "PRIVACY_POLICY",
  TERMS_OF_SERVICE: "TERMS_OF_SERVICE",
  TURN_IDEAS: "TURN_IDEAS",
  TURN_IDEAS_DESC: "TURN_IDEAS_DESC",
  GET_STARTED: "GET_STARTED",


  //Banner
  ACHIEVEMENTS: "ACHIEVEMENTS",
  ACHIEVEMENTS_DESC: "ACHIEVEMENTS_DESC",
  BUILD_YOUR: "BUILD_YOUR",
  DREAM_PRODUCT: "DREAM_PRODUCT",
  FASTER_DELIVERY: "FASTER_DELIVERY",
  BANNER_DESCRIPTION: "BANNER_DESCRIPTION",

  //Banner Card
  WEB_APP_TITLE: "WEB_APP_TITLE",
  WEB_APP_DESC: "WEB_APP_DESC",
  IT_CONSULTING_TITLE: "IT_CONSULTING_TITLE",
  IT_CONSULTING_DESC: "IT_CONSULTING_DESC",
  CUSTOM_SOFTWARE_TITLE: "CUSTOM_SOFTWARE_TITLE",
  CUSTOM_SOFTWARE_DESC: "CUSTOM_SOFTWARE_DESC",
  IOT_TITLE: "IOT_TITLE",
  IOT_DESC: "IOT_DESC",
  UI_UX_TITLE: "UI_UX_TITLE",
  UI_UX_DESC: "UI_UX_DESC",
  CYBERSECURITY_TITLE: "CYBERSECURITY_TITLE",
  CYBERSECURITY_DESC: "CYBERSECURITY_DESC"
};


export const t = (key, values = {}) => {
  return key;
};
